### ISSUE TITLE
Trouble setting up

### ISSUE THREAD

**Issue by jimmyeao** [mitchellrj/eufy_robovac#5]
Hi, I have my device ID and local key, and have followed the set up steps, however I get this in the logs:

> Sat Aug 24 2019 17:59:07 GMT+0100 (British Summer Time)
> eufy_vacuum: Error on device update!
> Traceback (most recent call last):
>   File "/config/custom_components/eufy_vacuum/tuya.py", line 466, in async_connect
>     sock.connect((self.host, self.port))
> socket.timeout: timed out
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 291, in _async_add_entity
>     await entity.async_device_update(warning=False)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 417, in async_device_update
>     await self.async_update()
>   File "/config/custom_components/eufy_vacuum/vacuum.py", line 75, in async_update
>     await self.robovac.async_get()
>   File "/config/custom_components/eufy_vacuum/tuya.py", line 489, in async_get
>     return await message.async_send(self, callback)
>   File "/config/custom_components/eufy_vacuum/tuya.py", line 327, in async_send
>     await device._async_send(self)
>   File "/config/custom_components/eufy_vacuum/tuya.py", line 553, in _async_send
>     await self.async_connect()
>   File "/config/custom_components/eufy_vacuum/tuya.py", line 468, in async_connect
>     raise ConnectionTimeoutException("Connection timed out") from e
> custom_components.eufy_vacuum.tuya.ConnectionTimeoutException: Connection timed out

**Comment by Joeboyc2** [comment]
see https://github.com/mitchellrj/eufy_robovac/issues/3

**Comment by mitchellrj** [comment]
Hopefully resolved with the latest code from `master`...

**Comment by jimmyeao** [comment]
```
eufy_vacuum: Error on device update!
Traceback (most recent call last):
  File "/config/custom_components/eufy_vacuum/tuya.py", line 482, in async_connect
    sock.connect((self.host, self.port))
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 439, in async_device_update
    await self.async_update()
  File "/config/custom_components/eufy_vacuum/vacuum.py", line 75, in async_update
    await self.robovac.async_get()
  File "/config/custom_components/eufy_vacuum/tuya.py", line 506, in async_get
    return await message.async_send(self, callback)
  File "/config/custom_components/eufy_vacuum/tuya.py", line 352, in async_send
    await device._async_send(self)
  File "/config/custom_components/eufy_vacuum/tuya.py", line 571, in _async_send
    await self.async_connect()
  File "/config/custom_components/eufy_vacuum/tuya.py", line 484, in async_connect
    raise ConnectionTimeoutException("Connection timed out") from e
custom_components.eufy_vacuum.tuya.ConnectionTimeoutException: Connection timed out
```

**Comment by mitchellrj** [comment]
This is a network error rather than a coding error.

What Robovac device are you using? What firmware version is it on? Are your home assistant host and the robovac on the same subnet?

**Comment by jimmyeao** [comment]
Yes, robovac 30c firmware is 1.1.4 everything on the same subnet.

Jimmy White
________________________________

**Comment by jimmyeao** [comment]
Just did a full rebuild of HASS and retried this - still the same result. Im am using HTTPS for HASS if that has any bearing on it

**Comment by jlockham** [comment]
did you get a solution for the error above 

Traceback (most recent call last):
  File "/config/custom_components/eufy_vacuum/tuya.py", line 482, in async_connect
    sock.connect((self.host, self.port))

As i have a 30C on firmware 1.1.6 and gettin gthe same error.
